services:
  web:
    build: .
    container_name: portfolio_web
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - portfolio_net

networks:
  portfolio_net:
    external: true
