/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./public/index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "rgb(var(--background))",
        foreground: "rgb(var(--foreground))",
        card: "rgb(var(--card))",
        "card-foreground": "rgb(var(--card-foreground))",
        popover: "rgb(var(--popover))",
        "popover-foreground": "rgb(var(--popover-foreground))",
        primary: "rgb(var(--primary))",
        "primary-foreground": "rgb(var(--primary-foreground))",
        secondary: "rgb(var(--secondary))",
        "secondary-foreground": "rgb(var(--secondary-foreground))",
        muted: "rgb(var(--muted))",
        "muted-foreground": "rgb(var(--muted-foreground))",
        accent: "rgb(var(--accent))",
        "accent-foreground": "rgb(var(--accent-foreground))",
        destructive: "rgb(var(--destructive))",
        "destructive-foreground": "rgb(var(--destructive-foreground))",
        border: "rgb(var(--border))",
        input: "rgb(var(--input))",
        "input-background": "rgb(var(--input-background))",
        "switch-background": "rgb(var(--switch-background))",
        ring: "rgb(var(--ring))",
        "chart-1": "rgb(var(--chart-1))",
        "chart-2": "rgb(var(--chart-2))",
        "chart-3": "rgb(var(--chart-3))",
        "chart-4": "rgb(var(--chart-4))",
        "chart-5": "rgb(var(--chart-5))",
        sidebar: "rgb(var(--sidebar))",
        "sidebar-foreground": "rgb(var(--sidebar-foreground))",
        "sidebar-primary": "rgb(var(--sidebar-primary))",
        "sidebar-primary-foreground": "rgb(var(--sidebar-primary-foreground))",
        "sidebar-accent": "rgb(var(--sidebar-accent))",
        "sidebar-accent-foreground": "rgb(var(--sidebar-accent-foreground))",
        "sidebar-border": "rgb(var(--sidebar-border))",
        "sidebar-ring": "rgb(var(--sidebar-ring))",
      },
      borderRadius: {
        sm: "calc(var(--radius) - 4px)",
        md: "calc(var(--radius) - 2px)",
        lg: "var(--radius)",
        xl: "calc(var(--radius) + 4px)",
      },
      fontSize: {
        xs: "var(--text-xs)",
        sm: "var(--text-sm)",
        base: "var(--text-base)",
        lg: "var(--text-lg)",
        xl: "var(--text-xl)",
        "2xl": "var(--text-2xl)",
        "3xl": "var(--text-3xl)",
        "4xl": "var(--text-4xl)",
        "5xl": "var(--text-5xl)",
        "6xl": "var(--text-6xl)",
        "7xl": "var(--text-7xl)",
      },
      fontWeight: {
        normal: "var(--font-weight-normal)",
        medium: "var(--font-weight-medium)",
      },
    },
  },
  plugins: [],
};
